### PR TITLE
Backport gjs 1.74.2, using mozjs102

### PR DESCRIPTION
**Pull request by mtwebster**
Backported from https://salsa.debian.org/gnome-team/gjs/-/commit/4a9f3edc475354cc8794d29784c5eaf25a8c4892 (1.74.2-1 bookworm tag).

### CODE REVIEW

**Comment by bobby285271** [comment]
Hi, I am getting this on NixOS unstable:

```
meson.build:612:4: ERROR: File installed-tests/js/org.cinnamon.CjsTest.gschema.xml does not exist.
```

https://github.com/linuxmint/cjs/blob/215aeee4e940dbd44daeb4281e5fb11406616da8/meson.build#L612

I wonder if some file rename will be needed here, or we just [disable/remove](https://github.com/linuxmint/cjs/blob/215aeee4e940dbd44daeb4281e5fb11406616da8/meson_options.txt#L15) `installed_tests` by default (this builds for me after that).

**Comment by mtwebster** [comment]
Sorry, try again.

I disabled the installed-tests by default also.

**Comment by ItzSwirlz** [comment]
+1, beat me to the punch with the test fix :) 

Can't test but it built with regular mozjs102 from the archive on Kinetic (22.10)

**Comment by mtwebster** [comment]
I've got mozjs102 building now on LMDE5 but cjs fails at the end of its build claiming it's missing dependency information for it. I don't get that in the Mint build.

https://github.com/linuxmint/cjs/actions/runs/3971311285/jobs/6808058677

Time for a break :)

**Comment by Fantu** [comment]
did some debian packaging improvements: https://github.com/linuxmint/cjs/pull/112
for now not tested and don't checked if symbols need update

**Comment by Cyanoxygen** [comment]
Hi folks, I am here to provide some information regarding cjs' js-102 port.

We recently updated the entire Cinnamon DE to [latest release of that time](https://github.com/AOSC-Dev/aosc-os-abbs/commits/stable/extra-cinnamon). But Cinnamon could not start, a little bit of debugging later it seems that it failed at the js-78 part.   
Sometime later I discovered this branch, and make our downstream packaging to track this branch, switched js-78 to js-102, and it worked perfectly (Ref: AOSC-Dev/aosc-os-abbs@d6d54877997c1b46c49110d9c061f705b749556b)

PR involved: AOSC-Dev/aosc-os-abbs#4399 (sorry, test results were not posted there)

**Comment by bobby285271** [comment]
> make our downstream packaging to track this branch, switched js-78 to js-102, and it worked perfectly

Weird, I think cinnamon 5.6.7 haven't adapted to cjs' js-102 port yet. I expect some changes will be needed on the cinnamon side (something like https://github.com/linuxmint/cinnamon/pull/9624) to make this work, e.g. when I run [nixosTests.cinnamon](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/cinnamon.nix) with a combination of cinnamon 5.6.7 and this branch I get:

Am I missing something?

```
machine # Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/org/Cinnamon”
machine # [   33.394816] su[1318]: pam_unix(su:session): session closed for user alice
machine # [   33.926575] .cinnamon-wrapp[1300]: JS ERROR: TypeError: can't redefine non-configurable property "setTimeout"
machine # installPolyfills@/nix/store/iyvmxk2pwhminwabv7l44n19pal4pi17-cinnamon-common-5.6.7/share/cinnamon/js/ui/overrides.js:246:12
machine # start@/nix/store/iyvmxk2pwhminwabv7l44n19pal4pi17-cinnamon-common-5.6.7/share/cinnamon/js/ui/main.js:269:21
machine # @<main>:1:47
machine # 
machine # [   33.931497] .cinnamon-wrapp[1300]: Execution of main.js threw exception: Script <main> threw an exception
```

**Comment by Cyanoxygen** [comment]
> Am I missing something?

Oh yeah, I forgot to mention that Cinnamon also have a branch corresponds this branch, with the same name. That branch has only one commit, you can just pick it and build. Sorry!

**Comment by Fantu** [comment]
hi, I see that someone have already started use next cjs, including in fedora (https://src.fedoraproject.org/rpms/cjs/) @leigh123linux and others that start use it: can you please tell me if you found bug/regression with latest stable cinnamon and its applets or seems "stable"?
Someone asked for it in debian but I don't had time to do testing relating recently.

**Comment by mtwebster** [comment]
5.7 wasn't intended to be a real 'release'- there's no tag, it was just to bump dependencies for cinnamon if we broke anything. It's now based on bookworm's release (I think) version - 1.74.2 instead of .1.

I've been running it since I opened this PR and haven't had any issues. Cinnamon will work with either 5.6 or new cjs as of https://github.com/linuxmint/cinnamon/commit/49567152ed8a813c8aeba5c4e0410c41bb06ec6f. No xlets are affected as far as I've seen. I don't think I've tried all of them, but close to it.

Most of my testing has been with 1.74.1, but I haven't seen any difference over the past week on 1.74.2.

**Comment by leigh123linux** [comment]
@Fantu  I switched to  a git snapshot for f39 because of this change.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/7PPI2WF3M5WJA6IKTVYN3U2I4GTCXQMI/

**Comment by jbicha** [comment]
@mtwebster By the way, [mozjs102](https://launchpad.net/ubuntu/+source/mozjs102) is now in Ubuntu 22.04 LTS.

**Pull request merged**
