### PR TITLE
Debian improvements

### PR DESCRIPTION
**Pull request by Fantu**
- remove d/control.in and add override about it in d/rules: it is no needed in cjs
- libcjs0f->libcjs0g, missed from gjs 1.70.0-4 rebase: there is a symbol remove from previous rebase so is better do the same dump of gjs
Note: when merged will require also change in d/control of cinnamon libcjs0f->libcjs0g

### CODE REVIEW

**Comment by Fantu** [comment]
the CI fails same of master branch, I don' have time to do a deep check now but from a fast look probably for lmde5 meson >=0.59 is needed and about mint21 fails one test, need to be checked is can be a real issue or only unexpected case from gjs->cjs

**Comment by Fantu** [comment]
after saw that package I start to prepare for debian experimental build successfull I tried to merge tests change but mint21 build still fails one test:
```
Summary of Failures:

 1/65 cjs:Scripts+thread-safe / CommandLine            FAIL             4.72s   45/46 subtests passed 
```

**Comment by Fantu** [comment]
@clefebvre @mtwebster instead of libcjs0f->libcjs0g I can do libcjs0f->libcjs0 to decrease difference with debian package, even if was not good on debian we keeped libcjs0 as was know that gjs was broken abi and as cjs is used only by cinnamon (that didn't bump libraries version when needed also in other components). and in future I hope will be bump when needed

**Comment by mtwebster** [comment]
The ci should work now -  the most recent 2 commits take care of it
- That test fails because it can't close a file descriptor it opens (no permission) - it succeeds everywhere else, including using circleci commands to build locally, so I think it's something with their cloud build system.
- Once that succeeded, it was failing by running out of memory during the build (the build server was using -j36). There's probably a correct way to solve it in the .circleci file (instance size or something) but I just limit the job count.

I'll have to see about what we want to do with the abi version - as you know we're resistant to package name changes :)

**Pull request closed without merging**
