### PR TITLE
Fixed gc https://github.com/linuxmint/cjs/issues/15

### PR DESCRIPTION
**Pull request by lestcape**
This is not my code, please see this issue:
https://github.com/linuxmint/cjs/issues/15
Credits to gnome shell devs... I only test this change and rename the things to cjs...

This pull can NOT resolve this issue:
https://github.com/linuxmint/Cinnamon/issues/3657

### CODE REVIEW

**Comment by clefebvre** [comment]
Upstream discussion https://bugzilla.gnome.org/show_bug.cgi?id=725099

**Comment by lestcape** [comment]
Thanks to take the time. The Upstream discussion also can be found on the comments of commits. Will be easy checked for any related change on the future.

**Comment by mtwebster** [comment]
Testing this - with your configurable menu, I still don't get memory freed - even if I force a GC from looking glass, it doesn't budge.  Started at 250mb for Cinnamon, it's at 570 after using the menu heavily for a minute or so.  I'll play a bit more later

**Comment by lestcape** [comment]
Thanks. I think, that there are more than two problems here, cairo context is not destroy explicit yet on Configurable Menu, and could be more memory problems on configurable Menu, specially when you change the themes... Additional if in a normal context you don't have memory problems you can not see a change... When i test this, i remove all external extensions include Configurable Menu. With the default cinnamon configuration i have memory problems, thats not occurs if the patch is set or i call periodically gc to destroy the memory. How i have memory problem without Configurable Menu, i can not be sure what functionality could cause a memory problem on Configurable Menu and i can not try to fix anything.

**Comment by lestcape** [comment]
What can i do to help? I can set the default cinnamon configuration again and repeat the test and report you what is currently occurs to me if you want...

**Comment by mtwebster** [comment]
Let me mess with it a bit more later (am at work now) - I just tried a quick before/after test - i'll likely end up merging it regardless.

**Comment by lestcape** [comment]
Ok, i added, that i note a higher memory problem when i add and remove the cinnamon menu, the procedure of change the theme on configurable menu is equivalent to add and remove the cinnamon menu, all actor are destroy and then is created again... I think that i can do this procedure only re-parent all actors with a lost cost of memory and time on the future.

**Pull request merged**
