### PR TITLE
Rebase off 1.70.0-4 (ubuntu 22.04)

### PR DESCRIPTION
**Pull request by mtwebster**

### CODE REVIEW

**Comment by jbicha** [comment]
By the way, Ubuntu 22.04 LTS will release with gjs 1.72 with [mozjs91](https://discourse.gnome.org/t/gnome-42-to-depend-on-spidermonkey-91/8665).

**Comment by mtwebster** [comment]
Since bullseye only has 78 we're going to stick with 1.70 here for at least the next release, unless there's some pressing need to do otherwise.

**Comment by Fantu** [comment]
@mtwebster I saw from https://tree.taiga.io/project/linuxmint-linux-mint-21-1/us/178 that cjs rebase result done, so is completed and working? no cinnamon changes are needed? or there are changes done in "muffin-5.2-test" branch related to this?

**Comment by ItzSwirlz** [comment]
IMO i'd wait for 22.04 to be released first, and then worry about a cjs 1.70 rebase. Plus, all these components need to be stable. Considering 22.04 will be using GNOME 42 (according to release schedule), components might break as I'm sure a lot of adjusting was put into GNOME's own applets to work.

**Comment by Fantu** [comment]
ubuntu 22.04 have already gjs 1.72.0-1 using mozjs91 but mtwebster wrote that on this rebase want remain with older using mozjs78

**Comment by jbicha** [comment]
> IMO i'd wait for 22.04 to be released first, and then worry about a cjs 1.70 rebase. Plus, all these components need to be stable. Considering 22.04 will be using GNOME 42 (according to release schedule), components might break as I'm sure a lot of adjusting was put into GNOME's own applets to work.

Let me clarify about GNOME. Debian Testing has gjs 1.72 now (the GNOME 42 series) and GNOME Shell 41 still works fine there. I don't remember gjs breaking GNOME apps since a few years.

From Debian's perspective, it would be great if Cinnamon would be ported to gjs 1.72 within about the next 8 months so that the next Debian Stable doesn't need to keep the obsolete mozjs78 around. By November, mozjs78 will have been unsupported for one year.

Do we need to try to push mozjs91 into Debian 11 "Bullseye" Backports? Debian's mozjs91 91.7.0-5 was adapted to use the internal ICU library so it should build ok on older or newer Debian-ish releases.

**Comment by mtwebster** [comment]
Sorry for not responding sooner.. 

We won't get to 1.72 for the coming release, but I'll try to manage it before the next debian stable.

I imagine we will need 91 in bullseye, as that's what LMDE5 is based on.

**Pull request merged**
